version: '3.8'
services:
  sanity:
    env_file:
      - .env
    image: sanity:latest
    restart: always
    environment:
      - NEXT_PUBLIC_SANITY_PROJECT_ID=$NEXT_PUBLIC_SANITY_PROJECT_ID
      - NEXT_PUBLIC_SANITY_DATASET=$NEXT_PUBLIC_SANITY_DATASET
    ports:
      - 3333:3333
    networks:
      - node

networks:
  node:
    driver: bridge