version: '3.8'
services:
  db:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    networks:
      - sonarnet
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5050:80
    networks:
      - sonarnet

  sonarqube:
    env_file:
      - .env
    image: sonarqube:latest
    restart: always
    environment:
      - SONARQUBE_JDBC_USERNAME=$SONARQUBE_JDBC_USERNAME
      - SONARQUBE_JDBC_PASSWORD=$SONARQUBE_JDBC_PASSWORD
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - sonarnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  sonarnet:
    driver: bridge

volumes:
  pg_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: